### ISSUE TITLE
./parseXMLblast.pl

### ISSUE THREAD

**Issue by yubau1112** [warrenlr/HLAminer#4]
$ ./parseXMLblast.pl

-bash: ./parseXMLblast.pl: /home/martink/bin/perl: bad interpreter: No such file or directory

How can I solve this?
thank you all

**Comment by warrenlr** [comment]
in : 
parseXMLblast.pl

replace the first line to : 

/usr/bin/perl  

(or type : which perl at the unix prompt and replace the first line to the full path of perl on your system.)

Alternatively, you may run : 

perl ./parseXMLblast.pl

--This will effectively bypass the first line of the perl script and execute with the specified perl on your system.
